### ISSUE TITLE
Error decoding HVAC IR code

### ISSUE THREAD

**Issue by tuzzmaniandevil** [probonopd/ProntoHex#3]
I hope this library is still maintained! :-)

I'm attempting to convert the following code which throws an exception:
`0000 006D 0000 0082 007D 003D 0010 000E 0010 000E 0010 002D 0010 000E 0010 002D 0010 000E 0010 000E 0010 000E 0010 002D 0010 002D 0010 000E 0010 000E 0010 000E 0010 002D 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 002D 0010 002D 0010 002D 0010 002D 0010 002D 0010 002D 0010 002D 0010 000E 0010 000E 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 000E 0010 002D 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 000E 0010 002D 0010 000E 0010 000E 0010 002D 0010 002D 0010 002D 0010 002D 0010 000E 0010 002D 0010 002D 0010 000E 0010 0ED1`

This is the stack trace:
```
Exception (28):
epc1=0x4000bf80 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3ffef040 end: 3ffef380 offset: 01a0

>>>stack>>>
3ffef1e0:  4020184d 00000030 00000018 ffffffff  
3ffef1f0:  006d0000 00820000 003d007d 000e0010  
3ffef200:  000e0010 002d0010 000e0010 002d0010  
3ffef210:  000e0010 000e0010 000e0010 002d0010  
3ffef220:  002d0010 000e0010 000e0010 000e0010  
3ffef230:  002d0010 002d0010 000e0010 000e0010  
3ffef240:  000e0010 000e0010 000e0010 000e0010  
3ffef250:  000e0010 000e0010 000e0010 000e0010  
3ffef260:  000e0010 000e0010 000e0010 002d0010  
3ffef270:  000e0010 000e0010 000e0010 000e0010  
3ffef280:  000e0010 000e0010 000e0010 002d0010  
3ffef290:  000e0010 000e0010 000e0010 000e0010  
3ffef2a0:  002d0010 002d0010 002d0010 002d0010  
3ffef2b0:  002d0010 002d0010 002d0010 002d0010  
3ffef2c0:  000e0010 000e0010 002d0010 000e0010  
3ffef2d0:  000e0010 000e0010 000e0010 000e0010  
3ffef2e0:  000e0010 000e0010 000e0010 002d0010  
3ffef2f0:  30313030 000e0000 000e0010 000e0010  
3ffef300:  0000008b 3ffe0010 00000000 000002b7  
3ffef310:  feefeffe 00000000 3ffee334 3ffee358  
3ffef320:  3ffe8698 00000000 3ffee334 40201ced  
3ffef330:  3fff07c4 0000052f 00000527 3fff028c  
3ffef340:  0000052f 00000527 00000000 00000000  
3ffef350:  00000000 feefeffe feefeffe feefeffe  
3ffef360:  3fffdad0 00000000 3ffee350 402028d8  
3ffef370:  feefeffe feefeffe 3ffee360 40100114  
<<<stack<<<
```

I used the example sketch and just replaced the pronto code. I have a ESP-12E dev board. TV Codes seem to work fine.

**Comment by probonopd** [comment]
Just guessing here, probably the code is too long to fit into some buffer. So the buffer needs to be increased. This is a typical issue in C. In `ProntoHex.cpp`, try increasing the sizes of buffers/arrays like `unsigned int convertedRaw[256];`, `uint16_t array[128];`, and so on.

**Comment by tuzzmaniandevil** [comment]
Thanks :-) I ended up doing a rewrite of the lib. https://github.com/tuzzmaniandevil/ProntoHex

**Comment by probonopd** [comment]
Interesting, thanks!
